<template>
  <div class="flex flex-col justify-center items-center  align-middle h-screen w-full">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="50px" height="50px" style="shape-rendering: auto; display: block; background: transparent;" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle fill="#0099e5" r="10" cy="50" cx="84">
    <animate begin="0s" keySplines="0 0.5 0.5 1" values="13;0" keyTimes="0;1" calcMode="spline" dur="1.1904761904761905s" repeatCount="indefinite" attributeName="r"></animate>
    <animate begin="0s" values="#0099e5;#0099e5;#34bf49;#ff4c4c;#0099e5" keyTimes="0;0.25;0.5;0.75;1" calcMode="discrete" dur="4.761904761904762s" repeatCount="indefinite" attributeName="fill"></animate>
</circle><circle fill="#0099e5" r="10" cy="50" cx="16">
  <animate begin="0s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="0;0;13;13;13" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="4.761904761904762s" repeatCount="indefinite" attributeName="r"></animate>
  <animate begin="0s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="16;16;16;50;84" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="4.761904761904762s" repeatCount="indefinite" attributeName="cx"></animate>
</circle><circle fill="#ff4c4c" r="10" cy="50" cx="50">
  <animate begin="-1.1904761904761905s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="0;0;13;13;13" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="4.761904761904762s" repeatCount="indefinite" attributeName="r"></animate>
  <animate begin="-1.1904761904761905s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="16;16;16;50;84" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="4.761904761904762s" repeatCount="indefinite" attributeName="cx"></animate>
</circle><circle fill="#34bf49" r="10" cy="50" cx="84">
  <animate begin="-2.380952380952381s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="0;0;13;13;13" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="4.761904761904762s" repeatCount="indefinite" attributeName="r"></animate>
  <animate begin="-2.380952380952381s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="16;16;16;50;84" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="4.761904761904762s" repeatCount="indefinite" attributeName="cx"></animate>
</circle><circle fill="#0099e5" r="10" cy="50" cx="16">
  <animate begin="-3.571428571428571s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="0;0;13;13;13" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="4.761904761904762s" repeatCount="indefinite" attributeName="r"></animate>
  <animate begin="-3.571428571428571s" keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1" values="16;16;16;50;84" keyTimes="0;0.25;0.5;0.75;1" calcMode="spline" dur="4.761904761904762s" repeatCount="indefinite" attributeName="cx"></animate>
</circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg>
  </div>
</template>