version: '3.8'

services:
  api:
    image: ${DOCKER_USERNAME}/vinylflamingo-feedback-api:latest
    build: !reset
    environment:
      - ENV=production
    volumes: !reset []
    env_file:
      - .env
