version: '3.8'

services:
  api:
    image: ${DOCKER_USERNAME}/vinylflamingo-feeback-api:latest
    environment:
      - ENV=production
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes: []
