services:
  api:
    image: ${DOCKER_USERNAME}/vinylflamingo-feedback-api:latest
    build: !reset
    environment:
      - ENV=production
    volumes: !reset []
    networks:
      - pinkproxy
    env_file:
      - .env
networks:
  pink-flamingo_pinkproxy:
    external: true

